[package]
name = "uniffi-bindgen"
version = "0.1.0"
rust-version.workspace = true
edition.workspace = true

[dependencies]
uniffi = { workspace = true, features = ["cli"] }
rat-object-detection = { path = "../../../packages/rs/rat-object-detection" }
