[package]
name = "rat-object-detection"
rust-version.workspace = true
edition.workspace = true
version.workspace = true

[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"
name = "rat_object_detection"

[features]
onnx-cuda = ["ort/cuda", "onnx-lib-load-dynamic"]
onnx-rocm = ["ort/rocm", "onnx-lib-load-dynamic"]
onnx-rknpu = ["ort/rknpu", "onnx-lib-load-dynamic"]
onnx-acl = ["ort/acl", "onnx-lib-load-dynamic"]
onnx-armnn = ["ort/armnn", "onnx-lib-load-dynamic"]
onnx-lib-load-dynamic = ["ort/load-dynamic"]
blas = ["ndarray/blas"]
default = ["blas"]
debug_embed = ["rust-embed/debug-embed"]

[dependencies]
ndarray = { version = "0.16.1", features = ["rayon"] }
strum = { workspace = true }
opencv = "0.94.1"
ort = { version = "2.0.0-rc.9" }
rust-embed = { workspace = true }
thiserror = { workspace = true }
eyre = { workspace = true }
uniffi = { workspace = true, features = ["cli"] }
num_cpus = { workspace = true }
half = { workspace = true }
num-traits = { workspace = true }
itertools = { workspace = true }
rand = { workspace = true }


[build-dependencies]
octocrab = { version = "^0.43.0", features = [] }
tokio = { workspace = true }
eyre = { workspace = true }
reqwest = { workspace = true }
tar = { workspace = true }
flate2 = { workspace = true }
bytes = { workspace = true }
